name: Build XCAN firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

      - name: Install toolchain
        run: sudo apt install -y gcc-arm-none-eabi dfu-util

      - name: Build firmware
        run: make canable
        env:
          MCU_SERIES: "F072"
          
      - name: Upload All Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: build-canable/* 
